# This is the main configuration file for the plugin.
# You can find more information about this file here:
# https://github.com/josantonius/minecraft-command

# Exclude operators from cooldown.
excludeOpsFromCooldowns: true

# Custom commands list.
commands: null