name: Command
version: 1.0.0
main: dev.josantonius.minecraft.command.Main
api-version: 1.19
author: Josantonius
description: Create custom commands with specific actions and cooldowns.

commands:
  command:
    description: Reload the plugin.
    usage: /command reload
    permission: command.admin
    permission-message: "&cYou don't have permission to use this command."
  
permissions:
  command.admin:
    default: op
    description: Allows the use of Command plugin commands